w3c/webtransport

index.html

Fix typos as well as duplicate definitions of `bidirectionalstream` and `receivestream`.

Fix typos and duplicate definitions

---

explainer.md
include/respec-config.js
index.html

Replace PooledHttpTransport and reference https://tools.ietf.org/html/draft-vvv-webtransport-http3-00

Add Http3Transport

---

index.bs
index.html

This basically is just reusing what was implemented in the RTCQuicTransport origin trial. Feel free to suggest removing/editing certain stats. The main motivation for this PR is:
1) Get basic stats in the spec
2) Have a place to point for at least some basic congestion control information exposed in the API.
See issues:
- https://github.com/w3c/webrtc-quic/issues/66 (Initial suggestion for P2P QUIC transport stats)
- https://github.com/WICG/web-transport/issues/21 (bandwidth prediction)

Adds getStats() method to QuicTransportBase.

---

index.bs
index.html

The URL scheme for QuicTransport is now defined in
https://tools.ietf.org/html/draft-vvv-webtransport-quic-01#section-6
Fixes #26

Use URL to identify QuicTransport

---

index.bs
index.html

Allow QuicTransport to connect to the servers not using a publicly trusted certificate.

---

index.bs

Section 16 only has examples for datagrams. Receiving chunks from `ReceiveStream`s is a little bit different from receiving datagrams. It requires developers to have a reader to get `ReceiveStream`s first, then another reader to read chunks from each `ReceiveStream`s.

Add an example for receiving from ReceiveStreams.

---

index.bs
index.html

The application error codes are 62-bit long:
https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-19.4
The 16-bit error code is probably a leftover from gQUIC, where they were
in fact 16-bit.

Make stream error codes 64-bit long

---

index.bs
index.html

Merge QuicTransport and Http3Transport interfaces into a single WebTransport interface

---

index.bs
index.html

This turns all getter methods for ReadableStreams and WritableStreams
into attirubtes, and renames some of them for clarity.
Fixes #54.
Fixes #101.
Fixes #132.
Fixes #133.

Turn some methods into attributes and rename them

---

index.bs

PR https://github.com/w3c/webtransport/pull/150 did not include the WebIDL for ready.  The problem was not caught because the PR evaluation process doesn't include a bikeshed compile automatic action (Issue https://github.com/w3c/webtransport/issues/108 )
Partial fix for Issue https://github.com/w3c/webtransport/issues/137

Add missing WebIDL for ready

---

use-cases.md

Per an action item at the W3C WebTransport TPAC [meeting #2](https://www.w3.org/wiki/WebTransport/TPAC_2020#WebTransport_WG_Virtual_Meeting_2:_Next_Steps), committing the collected use-cases as a new document.

Adding use-cases document

---

CONTRIBUTING.md

Please check:
1. @ylafon that I got the right patent policy links
2. @vasilvv I left the instructions for adding additional contributors the same though they differ from [other w3c specs](https://github.com/w3c/webrtc-pc/blob/master/CONTRIBUTING.md). Did they rely on WICG specific tooling? Do we want to keep them or converge?
3. Do we want to mention/give credit to WICG?

Update CONTRIBUTING.md to w3c.

---

.github/workflows/pr-push.yml

his should build the spec for every push to the main branch, result will be published in the gh-pages branch.

automatic spec build

---

index.bs

Fixes #104
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/173.html" title="Last updated on Dec 8, 2020, 8:55 AM UTC (334b17b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/173/5d38622...vasilvv:334b17b.html" title="Last updated on Dec 8, 2020, 8:55 AM UTC (334b17b)">Diff</a>

Remove arrayBuffer() mehtod.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/174
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/177.html" title="Last updated on Jan 6, 2021, 12:15 AM UTC (71db404)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/177/b8d1a94...aboba:71db404.html" title="Last updated on Jan 6, 2021, 12:15 AM UTC (71db404)">Diff</a>

Remove "consent freshness" requirement

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/182.html" title="Last updated on Jan 23, 2021, 1:28 AM UTC (b76e31a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/182/b8d1a94...jan-ivar:b76e31a.html" title="Last updated on Jan 23, 2021, 1:28 AM UTC (b76e31a)">Diff</a>

Improve examples.

---

index.bs

Fixes Issue https://github.com/w3c/webtransport/issues/193
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/194.html" title="Last updated on Feb 16, 2021, 2:12 PM UTC (c399ec3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/194/d1e913f...aboba:c399ec3.html" title="Last updated on Feb 16, 2021, 2:12 PM UTC (c399ec3)">Diff</a>

Fixes for Example 14.6

---

index.bs

Rebase of PR https://github.com/w3c/webtransport/pull/176
Fixes https://github.com/w3c/webtransport/issues/137
Related to Issue https://github.com/w3c/webtransport/issues/94
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/195.html" title="Last updated on Feb 16, 2021, 2:40 PM UTC (baf631c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/195/d1e913f...aboba:baf631c.html" title="Last updated on Feb 16, 2021, 2:40 PM UTC (baf631c)">Diff</a>

Mapping to QUIC

---

index.bs

Partial fix for Issue https://github.com/w3c/webtransport/issues/183
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/196.html" title="Last updated on Feb 16, 2021, 2:08 PM UTC (5cbf9b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/196/d1e913f...aboba:5cbf9b1.html" title="Last updated on Feb 16, 2021, 2:08 PM UTC (5cbf9b1)">Diff</a>

Single protocol decision/Removal of Quic-Transport

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/181. @yutakahirano I left _writeDatagrams_ and _readDatagrams_ to hook into. PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/192.html" title="Last updated on Feb 17, 2021, 2:55 PM UTC (d58bfdc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/192/edaead8...jan-ivar:d58bfdc.html" title="Last updated on Feb 17, 2021, 2:55 PM UTC (d58bfdc)">Diff</a>

Add transport.datagrams duplex stream + algorithm outline.

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/208.html" title="Last updated on Feb 18, 2021, 1:21 AM UTC (6071582)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/208/a813b4c...aboba:6071582.html" title="Last updated on Feb 18, 2021, 1:21 AM UTC (6071582)">Diff</a>

Update draft-vvv-webtransport-http3 reference

---

index.bs

I think we should coin `wt` the way WebSocket has coined `ws` , in all examples. Seems idiomatic and less intimidating. E.g.:
```js
const wt = new WebTransport(url);
const stream = await wt.createUnidirectionalStream();
await readableStreamOfTextData
.pipeThrough(new TextEncoderStream("utf-8"))
.pipeTo(stream.writable);
```
It also helps offset some of our long method names. 
```js
const decoder = new TextDecoderStream('utf-8');
for await (const data of wt.datagrams.readable.pipeThrough(decoder)) {
addToEventLog(`Datagram received: ${data}`);
}
```
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/209.html" title="Last updated on Feb 21, 2021, 12:21 AM UTC (fde077e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/209/099fd33...jan-ivar …

Use wt in examples in place of transport.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/111 by hitting the remaining instance left after https://github.com/w3c/webtransport/pull/202.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/203.html" title="Last updated on Feb 17, 2021, 8:41 PM UTC (65f3ffe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/203/a813b4c...jan-ivar:65f3ffe.html" title="Last updated on Feb 17, 2021, 8:41 PM UTC (65f3ffe)">Diff</a>

Fix remaining case of s/in background/in parallel/

---

index.bs

Fixes Issue https://github.com/w3c/webtransport/issues/204
This PR does not addressing pooling issues, such as removal of Stats that are inappropriate for pooled HTTP/3 connections.
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/205.html" title="Last updated on Mar 2, 2021, 11:47 PM UTC (cddc09e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/205/a813b4c...aboba:cddc09e.html" title="Last updated on Mar 2, 2021, 11:47 PM UTC (cddc09e)">Diff</a>

Remove remaining "For QUIC" and quic-transport references

---

index.bs

Fixes Issue https://github.com/w3c/webtransport/issues/200
***
<a href="https://pr-preview.s3.amazonaws.com/aboba/webtransport/pull/207.html" title="Last updated on Mar 3, 2021, 12:21 AM UTC (2f6f507)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/207/a813b4c...aboba:2f6f507.html" title="Last updated on Mar 3, 2021, 12:21 AM UTC (2f6f507)">Diff</a>

Acknowledgements section is wrong

---

index.bs

https://tools.ietf.org/html/... links for  QUIC-DATAGRAM and
WEBTRANSPORT-HTTPS sometimes return 404 and that makes
buildbots  unhappy (see
https://github.com/w3c/webtransport/pull/220/checks?check_run_id=2055921327
for example). Use https://datatracker.ietf.org/doc/... links instead
to mitigate the problem.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/224.html" title="Last updated on Mar 10, 2021, 7:35 AM UTC (6b85afe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/224/4ebe916...6b85afe.html" title="Last updated on Mar 10, 2021, 7:35 AM UTC (6b85afe)">Diff</a>

Replace IETF spec links

---

index.bs

This is for #128.
- Introduce WebTransportOptions.dedicated.
- Initialize a connection with
https://fetch.spec.whatwg.org/#concept-connection-obtain.
- (Bonus) Introduce WebTransport.Closed and reject it when the connection establishment fails.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/217.html" title="Last updated on Mar 9, 2021, 12:39 PM UTC (60dd39d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/217/4ebe916...60dd39d.html" title="Last updated on Mar 9, 2021, 12:39 PM UTC (60dd39d)">Diff</a>

Specify WebTransport initialization in more detail

---

index.bs

Booleans in Web IDL have the type `boolean`. The type `bool` does not exist.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/227.html" title="Last updated on Mar 16, 2021, 8:42 AM UTC (51185e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/227/02a7570...51185e8.html" title="Last updated on Mar 16, 2021, 8:42 AM UTC (51185e8)">Diff</a>

Fix Web IDL: "bool" -> "boolean"

---

index.bs

I couldn't find mention of the terms in the [Protocol Mappings table](https://w3c.github.io/webtransport/#protocol-mapping) in the referenced [WEB-TRANSPORT-HTTP3], so I added one to [[QUIC]] where they seem defined. @aboba PTAL.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/215.html" title="Last updated on Mar 3, 2021, 3:38 AM UTC (14cb4aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/215/4ebe916...jan-ivar:14cb4aa.html" title="Last updated on Mar 3, 2021, 3:38 AM UTC (14cb4aa)">Diff</a>

Reference QUIC as legend for the terms in the Protocol Mappings table.

---

index.bs

- Define `sendDatagrams` that can be called at any time.
- Specify timestamp and expiration duration handling in `writeDatagrams`.
Related to #179 and #187. This change adds internal slots but doesn't change the public interface.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/220.html" title="Last updated on Mar 30, 2021, 11:13 PM UTC (5563691)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/220/5b746e5...5563691.html" title="Last updated on Mar 30, 2021, 11:13 PM UTC (5563691)">Diff</a>

Specify "writeDatagrams" in more detail

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/210.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/233.html" title="Last updated on Mar 30, 2021, 8:34 PM UTC (0b97716)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/233/5b746e5...jan-ivar:0b97716.html" title="Last updated on Mar 30, 2021, 8:34 PM UTC (0b97716)">Diff</a>

Make ReceiveStream readable, and SendStream writable.

---

index.bs

- Stop defining internal slots in the constructor and have tables
for internal slots instead.
- Remove "internal slots" words as they are redundant.
- Replace \{{[[slot]]}} with \[=[[slot]]=].
Fixes #222 
Fixes #223
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/244.html" title="Last updated on Apr 13, 2021, 9:10 PM UTC (5887633)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/244/87bcbf1...5887633.html" title="Last updated on Apr 13, 2021, 9:10 PM UTC (5887633)">Diff</a>

[Editorial] Tidy up "internal slots"

---

index.bs

- Define readDatagrams that can be called at any time.
- Rename receiveDatagrams with pullDatagrams as now incoming
datagrams are a pull source rather than a push source.
- Fix creation of incomingDatagrams and outgoingDatagrams (#247).
- Add IncomingDatagramsHighWaterMark and
IncomingDatagramsExpirationDuration (#221).
Fixes #247.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/249.html" title="Last updated on Apr 28, 2021, 8:22 AM UTC (b2e268f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/249/8795cb1...b2e268f.html" title="Last updated on Apr 28, 2021, 8:22 AM UTC (b2e268f)">Diff</a>

Specify incoming datagrams in more detail

---

index.bs

- Define WebTransport session and stream.
- Define capabilities and map them with the protocol spec.
- Fix existing use of the capabilities.
- _receiveDatagrams_
- _sendDatagrams_
- WebTransport constructor
- WebTransport.prototype.close
Fixes #250.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/253.html" title="Last updated on May 10, 2021, 4:00 AM UTC (0568af5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/253/1c96d59...0568af5.html" title="Last updated on May 10, 2021, 4:00 AM UTC (0568af5)">Diff</a>

Define WebTransport session and stream

---

index.bs

This is a mostly editorial change.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/258.html" title="Last updated on May 11, 2021, 10:08 AM UTC (9c3b341)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/258/a19a918...9c3b341.html" title="Last updated on May 11, 2021, 10:08 AM UTC (9c3b341)">Diff</a>

Merge DatagramTransport mixin into WebTransport

---

index.bs

This is similar to #258.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/261.html" title="Last updated on May 13, 2021, 5:36 AM UTC (403ea58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/261/91ae9d6...403ea58.html" title="Last updated on May 13, 2021, 5:36 AM UTC (403ea58)">Diff</a>

[Mostly editorial] Merge BidirectionalStreamsTransport into WebTransport

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/242.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/248.html" title="Last updated on May 13, 2021, 11:49 PM UTC (dc1790c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/248/a19a918...jan-ivar:dc1790c.html" title="Last updated on May 13, 2021, 11:49 PM UTC (dc1790c)">Diff</a>

Rename abortWriting()/writingAborted → reset()/remoteCanceled & abortReading()/readingAborted → cancel()/remoteReset

---

index.bs

Create the ReadableStream explicitly.
This is for #185.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/266.html" title="Last updated on Jun 14, 2021, 5:06 AM UTC (ab0e271)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/266/7b0630a...ab0e271.html" title="Last updated on Jun 14, 2021, 5:06 AM UTC (ab0e271)">Diff</a>

Define WebTransport.incomingBidirectionalStreams in more detail

---

index.bs

...as a shorthand of "queue a global task on the network task
source". This is an editorial change.
Currently there is only one usage but I expect more in the future.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/274.html" title="Last updated on Jun 14, 2021, 8:24 AM UTC (9da5254)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/274/7b0630a...9da5254.html" title="Last updated on Jun 14, 2021, 8:24 AM UTC (9da5254)">Diff</a>

Define "queue a network task"

---

index.bs

Define the following attributes on DatagramDuplexStream.
- incomingMaxAge
- outgoingMaxAge
- incomingHighWaterMark
- outgoingHighWaterMark
Fixes #251, #221, #152
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/267.html" title="Last updated on Jun 16, 2021, 4:59 AM UTC (4c11ddc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/267/dec79ad...4c11ddc.html" title="Last updated on Jun 16, 2021, 4:59 AM UTC (4c11ddc)">Diff</a>

Define datagram backpressure control attributes

---

index.bs

This is a follow-up change of #266.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/276.html" title="Last updated on Jun 14, 2021, 6:25 AM UTC (7a58b9b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/276/2a0ca65...7a58b9b.html" title="Last updated on Jun 14, 2021, 6:25 AM UTC (7a58b9b)">Diff</a>

Fix the protocol link of "receiving a bidirectional stream"

---

index.bs

This is a follow-up change of #266.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/278.html" title="Last updated on Jun 14, 2021, 10:04 AM UTC (a2c2cb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/278/dec79ad...a2c2cb5.html" title="Last updated on Jun 14, 2021, 10:04 AM UTC (a2c2cb5)">Diff</a>

[Editorial] Replace "remote host" with "server"

---

index.bs

- Use [=queue a network task=] (which is a shorthand of
[=queue a global task=]) for logic that should be run in the
same sequences/threads where the script runs.
- Replace [=queue a global task=] with [=queue a network task=].
- Make some trivial fixes for getStats().
This change leaves createBidirectionalStream() as is because I'm
planning to overhaul it.
Fixes #112.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/279.html" title="Last updated on Jun 16, 2021, 7:10 AM UTC (a3a7117)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/279/dec79ad...a3a7117.html" title="Last updated on Jun 16, 2021, 7:10 AM UTC (a3a7117)">Diff</a>

Run steps in correct sequences/tasks

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/256.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/285.html" title="Last updated on Jun 22, 2021, 9:33 PM UTC (ce64700)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/285/1cb3edc...jan-ivar:ce64700.html" title="Last updated on Jun 22, 2021, 9:33 PM UTC (ce64700)">Diff</a>

Make API [SecureContext]

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/271.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/286.html" title="Last updated on Jun 22, 2021, 9:41 PM UTC (3ab2915)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/286/1cb3edc...jan-ivar:3ab2915.html" title="Last updated on Jun 22, 2021, 9:41 PM UTC (3ab2915)">Diff</a>

Remove stream.remoteCanceled and stream.remoteReset promises

---

index.bs

- Specify write, close and abort algorithms for SendStream.
- Specify the behavior for STOP_SENDING signal.
This is for #185.
Fixes #259.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/283.html" title="Last updated on Jun 23, 2021, 3:51 AM UTC (4a95cd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/283/bf4d9cd...4a95cd3.html" title="Last updated on Jun 23, 2021, 3:51 AM UTC (4a95cd3)">Diff</a>

Specify SendStream algorithms

---

index.bs

- Define [[IncomingUnidirectionalStreams]] and set it up at the constructor.
- Remove logic from `"closed"` and `"failed"` states - they are specified in
[=WebTransport/cleanup=].
- Remove [[ReceivedStreams]] which have been very confusing with
[[ReceiveStreams]]. (We need more work to remove [[OutgoingStreams]]).
- Add cleanup steps of [[IncomingBidirectionalStreams]] and
[[IncomingUnidirectionalStreams]] to [=WebTransport/cleanup=].
Related to #268 and #185.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/282.html" title="Last updated on Jun 23, 2021, 4:28 AM UTC (5eb9e86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/282/94a6e0c...5eb9e86.html" title="Last updated on Jun 23, 2021, 4:28 AM UTC (5eb9e86)">Diff</a>

Define [[IncomingUnidirectionalStreams]]

---

index.bs

Rewrite it in the same manner with createUnidirectionalStream().
This is a follow-up of #266.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/280.html" title="Last updated on Jun 22, 2021, 11:08 PM UTC (c8089e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/280/dec79ad...c8089e5.html" title="Last updated on Jun 22, 2021, 11:08 PM UTC (c8089e5)">Diff</a>

Modernize createBidirectionalStream()

---

index.bs

Purely editorial.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/290.html" title="Last updated on Jun 23, 2021, 6:01 AM UTC (7f17200)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/290/5a08bf8...7f17200.html" title="Last updated on Jun 23, 2021, 6:01 AM UTC (7f17200)">Diff</a>

Merge consecutive "Procedures" sections in ReceiveStream

---

index.bs

Let's use "incoming unidirectional" and "outgoing unidirectional"
instead of "incoming" and "outgoing" for WebTransport stream.
This is a follow-up of #283.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/289.html" title="Last updated on Jun 23, 2021, 5:57 AM UTC (d3a1271)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/289/5a08bf8...d3a1271.html" title="Last updated on Jun 23, 2021, 5:57 AM UTC (d3a1271)">Diff</a>

"incoming unidirectional" and "outgoing unidirectional" streams

---

index.bs

Have SendStream's write and close abortable with
WritableStreamDefaultController.signal.
Remove SendStream.reset as it's now covered by abort().
Fixes #260.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/295.html" title="Last updated on Jun 25, 2021, 3:24 PM UTC (95c2a3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/295/4571dcf...95c2a3b.html" title="Last updated on Jun 25, 2021, 3:24 PM UTC (95c2a3b)">Diff</a>

Have SendStream's write/close abortable

---

index.bs

- Stop using promises.
- Take care of the case where close() is called while connecting.
- Take care of the race between the session establishment and
transport closure/error.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/296.html" title="Last updated on Jun 30, 2021, 7:30 AM UTC (6809dab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/296/4571dcf...6809dab.html" title="Last updated on Jun 30, 2021, 7:30 AM UTC (6809dab)">Diff</a>

Refine session establishment error logic

---

index.bs

Before this change, #webtransport-session links to
"WebTransport session" and #webtransport-session① links to
"[[Session]]" for="WebTransport.
In order to have a public link to "[[Session]]" at
https://github.com/whatwg/html/pull/6856, add "for=protocol" to
the definition of "WebTransport session".
With this change #protocol-webtransport-session links to
"WebTransport session", and #webtransport-session links to
[[Session]].
This is for #127.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/308.html" title="Last updated on Jul 14, 2021, 5:13 AM UTC (62d9386)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/308/3be0e20...62d9386.html" title="Last updated on Jul 14, 2021, 5:13 AM UTC (62d9386)">Diff</a>

Make "WebTransport session" scoped

---

index.bs

pullBidirectionalStream and pullUnidirectionalStream can be called
when transport's state is "connecting". In that case we need to
wait for transport's ready promise.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/304.html" title="Last updated on Jul 7, 2021, 4:27 AM UTC (52de6ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/304/da0b77e...52de6ea.html" title="Last updated on Jul 7, 2021, 4:27 AM UTC (52de6ea)">Diff</a>

Incoming streams' pull algorithms should work even when unready

---

index.bs

This is for #127.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/309.html" title="Last updated on Jul 14, 2021, 11:14 AM UTC (1f1f818)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/309/f87c99e...1f1f818.html" title="Last updated on Jul 14, 2021, 11:14 AM UTC (1f1f818)">Diff</a>

Terminate WebTransport sessions when unloading page

---

index.bs

SendStream.remoteCancelled has been removed. Remove the now
unused interface and a step that were for the property.
Related to #260.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/310.html" title="Last updated on Jul 15, 2021, 4:45 AM UTC (ef8fdba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/310/f87c99e...ef8fdba.html" title="Last updated on Jul 15, 2021, 4:45 AM UTC (ef8fdba)">Diff</a>

Remove StreamAbortInfo and a step for remoteCancelled

---

index.bs

Have it a spec-only concept for streams created by the
"create a SendStream" procedure.
This is for #306.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/307.html" title="Last updated on Jul 16, 2021, 8:07 AM UTC (d6b9c09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/307/3be0e20...d6b9c09.html" title="Last updated on Jul 16, 2021, 8:07 AM UTC (d6b9c09)">Diff</a>

Remove "SendStream" Web IDL interface

---

index.bs

Define pullAlgorithm and cancelAlgorithm, and set up ReceiveStream
with them.
This relies on https://github.com/whatwg/streams/pull/1130.
Fixes #185.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 29, 2021, 2:42 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebtransport%2Fe23c9c325fb45ba758701e943a496e25da6e8867%2Findex.bs&md-warning=not%20ready)
```
<html><body><p><strong>WARNING: …
```

Set up ReceiveStream with proper algorithms

---

index.bs

Have it a spec-only concept for streams created by the
"create a ReceiveStream" procedure.
Fixes #306.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/318.html" title="Last updated on Aug 2, 2021, 3:09 PM UTC (8acba74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/318/d1be624...8acba74.html" title="Last updated on Aug 2, 2021, 3:09 PM UTC (8acba74)">Diff</a>

Remove "ReceiveStream" Web IDL interface

---

index.bs

Introduce WebTransportError, an interface for error information
related to WebTransport.
This is related to #252. This is based on #288. This PR is aiming to land
a minimal change in order to unblock other issues. For example, we're
talking about `errorSource` in #288. This PR doesn't contain it.
In the last WG meeting, no one was against introducing this interface, and
people prefered having one interface and multiple properties to having
multiple error interfaces and fewer properties. Hence the contents
of this shouldn't be super controversial I believe.
This change addresses most of comments made by @ricea at #288. One exception
is how to handle out-of-range value. I think it is the same problem as #214, and
should be solved altogether.
I want to merge this PR at the next WG meeting …

Introduce WebTransportError

---

index.bs

Fixes #225.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/321.html" title="Last updated on Aug 4, 2021, 4:18 AM UTC (c91f1ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/321/7bfb7ca...c91f1ac.html" title="Last updated on Aug 4, 2021, 4:18 AM UTC (c91f1ac)">Diff</a>

Active WebTransport must not be collected

---

index.bs

Fixes #284.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/322.html" title="Last updated on Aug 4, 2021, 5:06 AM UTC (fe051d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/322/7bfb7ca...fe051d5.html" title="Last updated on Aug 4, 2021, 5:06 AM UTC (fe051d5)">Diff</a>

Allow BufferSources for outgoing bytes

---

index.bs

Removing hanging quote from non-normative example script
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 9, 2021, 4:25 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebtransport%2F01e8dbb695caf7d3ea557491deda4de57fa1cd8b%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 1.
Traceback (most recent call last):
File "/sites/api.csswg.org/bikeshed/bikeshed.py", …
```

Fixing example script

---

index.bs

- Define the internal slot.
- Use the internal slot in writeDatagram and sendDatagram.
- Wire up the internal slot and the attribute.
Fixes #301 and #302.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/311.html" title="Last updated on Aug 17, 2021, 11:02 AM UTC (309496c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/311/2fe564d...309496c.html" title="Last updated on Aug 17, 2021, 11:02 AM UTC (309496c)">Diff</a>

Define DatagramDuplexStream.maxDatagramSize

---

index.bs

Fixes #214.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/323.html" title="Last updated on Aug 17, 2021, 11:41 AM UTC (e4ee7a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/323/2fe564d...e4ee7a5.html" title="Last updated on Aug 17, 2021, 11:41 AM UTC (e4ee7a5)">Diff</a>

Use [Clamp] for WebTransportErrorInit.applicationProtocolCode

---

index.bs

Specify how to calculate the application protocol error code in
SendStream/abort and ReceiveStream/cancel.
When no code is provided, use 0 as the fallback.
Fixes #294.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/327.html" title="Last updated on Aug 17, 2021, 11:39 PM UTC (bc3696c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/327/2fe564d...bc3696c.html" title="Last updated on Aug 17, 2021, 11:39 PM UTC (bc3696c)">Diff</a>

Specify reason handling in abort() and cancel()

---

index.bs

...to allow web developers to distinguish
stream/session/connection errors.
Fixes #252.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/329.html" title="Last updated on Aug 17, 2021, 11:50 PM UTC (9b6f389)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/329/2fe564d...9b6f389.html" title="Last updated on Aug 17, 2021, 11:50 PM UTC (9b6f389)">Diff</a>

Introduce WebTransportError/source

---

index.bs

Fixes #199.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/330.html" title="Last updated on Aug 18, 2021, 1:58 AM UTC (9252281)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/330/8073da6...9252281.html" title="Last updated on Aug 18, 2021, 1:58 AM UTC (9252281)">Diff</a>

Prefix BidirectionalStream and DatagramDuplexStream with WebTransport

---

index.bs

Fixes #333.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/337.html" title="Last updated on Aug 24, 2021, 11:46 AM UTC (b9b39b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/337/f0d9aa6...b9b39b6.html" title="Last updated on Aug 24, 2021, 11:46 AM UTC (b9b39b6)">Diff</a>

Deal with send failures in SendStream/write

---

index.bs

Discussed at #62. Explicitly state that outgoing datagrams are
prioritized for now. We will introduce a way to change this
default behavior, as part of the prioritization API.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/340.html" title="Last updated on Aug 31, 2021, 11:10 AM UTC (4122fe6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/340/f0d9aa6...4122fe6.html" title="Last updated on Aug 31, 2021, 11:10 AM UTC (4122fe6)">Diff</a>

Prioritize outgoing datagrams over stream data

---

index.bs

Mis-indented notes reset list items. This change fixes that.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/347.html" title="Last updated on Sep 2, 2021, 4:57 AM UTC (40113d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/347/5bf0bba...40113d0.html" title="Last updated on Sep 2, 2021, 4:57 AM UTC (40113d0)">Diff</a>

Fix indentation of notes

---

index.bs

...and replace TBDs with WebTransportError creations.
Fixes #334, #336 and #338.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/335.html" title="Last updated on Sep 2, 2021, 5:54 AM UTC (8cc2cec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/335/cea6958...8cc2cec.html" title="Last updated on Sep 2, 2021, 5:54 AM UTC (8cc2cec)">Diff</a>

Define WebTransportError/create

---

index.bs

Replace some TypeError occurences with WebTransportError. I didn't
replace type related errors such as the case where writeDatagrams is
called with a value that is not a BufferSource.
Fixes #344.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/346.html" title="Last updated on Sep 6, 2021, 5:13 AM UTC (1a7b710)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/346/bf1ec50...1a7b710.html" title="Last updated on Sep 6, 2021, 5:13 AM UTC (1a7b710)">Diff</a>

Replace TypeError with WebTransportError

---

index.bs

Mostly mechanical. Some manual edits to maintain the alphabetical
ordering.
Fixes #328.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/348.html" title="Last updated on Sep 3, 2021, 1:28 PM UTC (29a0484)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/348/bf1ec50...29a0484.html" title="Last updated on Sep 3, 2021, 1:28 PM UTC (29a0484)">Diff</a>

Replace applicationProtocolCode with streamErrorCode

---

index.bs

- Deal with closeInfo.reason in WebTransport.close(closeInfo).
- Explicitly state the code and reason are optional in
session/terminate.
- Change the type of WebTransportCloseInfo.errorCode based
on [1].
- Remove default values of errorCode and reason from
WebTransportCloseInfo, given they are optional.
1: https://mailarchive.ietf.org/arch/msg/webtransport/P6jXBCOwCgqHlmY-DEKDpot6ZII/
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/343.html" title="Last updated on Sep 7, 2021, 2:59 AM UTC (8e03a39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/343/cea6958...8e03a39.html" title="Last updated on Sep 7, 2021, 2:59 AM UTC (8e03a39)">Diff</a>

Deal with the reason string in WebTransport.close()

---

index.bs

See https://github.com/whatwg/fetch/pull/1259 for context. This change should be a no-op.
***
<a href="https://pr-preview.s3.amazonaws.com/annevk/webtransport/pull/351.html" title="Last updated on Sep 8, 2021, 4:56 PM UTC (b254896)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/351/54ea041...annevk:b254896.html" title="Last updated on Sep 8, 2021, 4:56 PM UTC (b254896)">Diff</a>

Fetch's obtain a connection changed slightly

---

index.bs

Fixes #342.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/356.html" title="Last updated on Sep 16, 2021, 10:10 AM UTC (ce97cab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/356/9ff7a84...ce97cab.html" title="Last updated on Sep 16, 2021, 10:10 AM UTC (ce97cab)">Diff</a>

Rename WebTransportCloseInfo/errorCode to closeCode

---

index.bs

Currently it's DOMString, but that led to some complexity such as case sensitivity. This PR changes
the type to BufferSource, so that we can use the simple byte sequence comparison.
Fixes #355.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/358.html" title="Last updated on Sep 24, 2021, 1:11 AM UTC (763c7a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/358/2a34434...763c7a7.html" title="Last updated on Sep 24, 2021, 1:11 AM UTC (763c7a7)">Diff</a>

Use BufferSource for the hash value

---

index.bs

Use |transport|'s relevant settings object's origin.
Fixes #368.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/370.html" title="Last updated on Oct 13, 2021, 7:22 AM UTC (bb1edc4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/370/a0e5591...bb1edc4.html" title="Last updated on Oct 13, 2021, 7:22 AM UTC (bb1edc4)">Diff</a>

Explicitly provide the "Origin" header on session establishment

---

index.bs

The section seems lost in a past cleanup change.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/364.html" title="Last updated on Oct 20, 2021, 7:56 AM UTC (2803522)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/364/ab5a4e2...2803522.html" title="Last updated on Oct 20, 2021, 7:56 AM UTC (2803522)">Diff</a>

Describe BidirectionalStream's attributes

---

index.bs

We only need the pre-request check. We don't need the post-request
check given there is no redirects on WebTransport.
This is for #59.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/367.html" title="Last updated on Oct 20, 2021, 7:50 AM UTC (e1a7f10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/367/0a62f0c...e1a7f10.html" title="Last updated on Oct 20, 2021, 7:50 AM UTC (e1a7f10)">Diff</a>

Add Content Security Policy check on request

---

index.bs

In looking into this text and the related specifications I decided that
it would be better to address the risk of request forgery in the
protocol specifications.  Right now, they say nothing about this
problem, but they really should.  I'm going to open an issue.
On the assumption that the protocol documents address this problem
adequately, then this document doesn't need to concern itself with the
problem.  It is enough to remove any false claims and defer to the
protocol spec.
This contains a tweak to the adjacent text for the Origin field (#368),
but it doesn't fix that issue.
Closes #175.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/webtransport/pull/369.html" title="Last updated on Nov 23, 2021, 3:30 PM UTC (dd62f07)">Preview</a> | <a …

Remove text on request forgery

---

index.bs

Update spec as `WritableStreamDefaultController.abortReason` was removed in https://github.com/whatwg/streams/pull/1177, and AbortSignal now has an "abort reason" property (i.e. `signal.reason` based on https://github.com/whatwg/dom/pull/1027) that can be used instead for aborting a SendStream.
@yutakahirano Is it okay if you could take a look?
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/377.html" title="Last updated on Dec 2, 2021, 6:05 AM UTC (1378bfe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/377/b68a616...nidhijaju:1378bfe.html" title="Last updated on Dec 2, 2021, 6:05 AM UTC (1378bfe)">Diff</a>

Use AbortSignal's abort reason to abort SendStream

---

index.bs

Fixes #366.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/379.html" title="Last updated on Dec 8, 2021, 12:15 AM UTC (4dd63c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/379/3ddc1a8...4dd63c7.html" title="Last updated on Dec 8, 2021, 12:15 AM UTC (4dd63c7)">Diff</a>

Make code and reason WebTransportCloseInfo non-optional

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/229.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/378.html" title="Last updated on Dec 7, 2021, 4:44 PM UTC (1bdb11e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/378/3ddc1a8...jan-ivar:1bdb11e.html" title="Last updated on Dec 7, 2021, 4:44 PM UTC (1bdb11e)">Diff</a>

Block ports on fetch's bad ports list & use WebTransportError for it and CSP.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/374.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/386.html" title="Last updated on Feb 2, 2022, 12:34 AM UTC (5577154)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/386/fca64e2...jan-ivar:5577154.html" title="Last updated on Feb 2, 2022, 12:34 AM UTC (5577154)">Diff</a>

Add smoothedRtt & rttVariation to WebTransportStats

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/373.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/387.html" title="Last updated on Feb 15, 2022, 3:19 PM UTC (dfabdc9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/387/fca64e2...jan-ivar:dfabdc9.html" title="Last updated on Feb 15, 2022, 3:19 PM UTC (dfabdc9)">Diff</a>

Add packetsLost to WebTransportStats.

---

index.bs

This adds extra requirements on custom certificates used by
WebTransportHash API, as well as adds a discussion concerning the
security properties of those into Security Considerations section.
Fixes #349.
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/375.html" title="Last updated on Dec 9, 2021, 10:50 PM UTC (e35741a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/375/5b0a9ec...vasilvv:e35741a.html" title="Last updated on Dec 9, 2021, 10:50 PM UTC (e35741a)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/375.html" title="Last updated on Feb 4, 2022, 6:14 PM UTC (5d6b3d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/375/5b0a9ec...vasilvv:5d6b3d2.html" …

Elaborate requirements on custom certificate hashes

---

.github/workflows/pr-push.yml
index.bs

Using infrastructure provided by bikeshed
(deleted #390 by mistake)
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 23, 2022, 6:01 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fdontcallmedom%2Fwebtransport%2F2b47c11fdce46c9edee6a323a2e7fba01ff9336f%2Findex.bs&md-warning=not%20ready)
```
<html><body><p><strong>WARNING: </strong>mysqli_connect(): (HY000/2002): Can't connect to local MySQL server …
```

 Improve markup for definitions and automatic links

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/107.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/385.html" title="Last updated on Mar 31, 2022, 3:48 PM UTC (73518d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/385/e3f77e5...jan-ivar:73518d8.html" title="Last updated on Mar 31, 2022, 3:48 PM UTC (73518d8)">Diff</a>

Add wt.reliability attr and {requireUnreliable} constructor option.

---

index.bs

Fixes #382.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/397.html" title="Last updated on Apr 22, 2022, 3:13 AM UTC (19d25ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/397/23a4ef4...19d25ba.html" title="Last updated on Apr 22, 2022, 3:13 AM UTC (19d25ba)">Diff</a>

Ensure the reason string is valid even when clipped

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/372.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/395.html" title="Last updated on Apr 27, 2022, 5:11 PM UTC (030e1ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/395/23a4ef4...jan-ivar:030e1ca.html" title="Last updated on Apr 27, 2022, 5:11 PM UTC (030e1ca)">Diff</a>

Add per-stream getStats().

---

index.bs

removed extra (and unclosed) empty \<tr>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/403.html" title="Last updated on Jun 24, 2022, 8:40 AM UTC (007475c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/403/3da2076...007475c.html" title="Last updated on Jun 24, 2022, 8:40 AM UTC (007475c)">Diff</a>

html validity

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/365.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/406.html" title="Last updated on Aug 30, 2022, 2:20 PM UTC (3f4b036)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/406/71ee094...jan-ivar:3f4b036.html" title="Last updated on Aug 30, 2022, 2:20 PM UTC (3f4b036)">Diff</a>

Add congestionControl contructor arg and readonly attribute

---

index.bs

To standalone spec instead of HTML
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/webtransport/pull/418.html" title="Last updated on Sep 8, 2022, 11:55 AM UTC (c42342a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/418/bc732e3...dontcallmedom:c42342a.html" title="Last updated on Sep 8, 2022, 11:55 AM UTC (c42342a)">Diff</a>

Update link to websockets spec

---

index.bs

They [used to be](https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/275.html#bidirectional-stream) `ReceiveStream` and `SendStream` but lost their types during the conversion to simple `ReadableStream` and `WritableStream` and back.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/423.html" title="Last updated on Oct 6, 2022, 12:29 AM UTC (172c906)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/423/a8fec03...jan-ivar:172c906.html" title="Last updated on Oct 6, 2022, 12:29 AM UTC (172c906)">Diff</a>

BidirectionalStream's readable and writable lost their types.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/402. Also adds note with a link to the streams spec on this.
Also tries to use `bytes` vs `data` consistently to distinguish encoded vs decoded data respectively.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/434.html" title="Last updated on Nov 9, 2022, 9:25 PM UTC (d914daf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/434/f2fe7de...jan-ivar:d914daf.html" title="Last updated on Nov 9, 2022, 9:25 PM UTC (d914daf)">Diff</a>

Update examples to not await write(bytes)

---

index.bs

Fixes #424.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/433.html" title="Last updated on Dec 1, 2022, 8:54 PM UTC (14b9ae6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/433/f2fe7de...jan-ivar:14b9ae6.html" title="Last updated on Dec 1, 2022, 8:54 PM UTC (14b9ae6)">Diff</a>

Make WebTransportSendStream & WebTransportReceiveStream transferable.

---

index.bs

Fixed #431.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/438.html" title="Last updated on Dec 20, 2022, 6:12 AM UTC (44b090b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/438/87df5e2...jan-ivar:44b090b.html" title="Last updated on Dec 20, 2022, 6:12 AM UTC (44b090b)">Diff</a>

Add order option to createUnidirectionalStream().

---

index.bs

Fixes: https://github.com/w3c/webtransport/issues/435
Note: Writing datagrams while the transport's state  is `"connecting"` is already allowed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/440.html" title="Last updated on Dec 4, 2022, 11:55 PM UTC (84e4710)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/440/5841bfe...84e4710.html" title="Last updated on Dec 4, 2022, 11:55 PM UTC (84e4710)">Diff</a>

Allow opening streams in parallel to the CONNECT request

---

index.bs

Fixes #428. Contains tentative language based on assumptions in https://github.com/w3c/webtransport/pull/438.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/441.html" title="Last updated on Dec 7, 2022, 11:05 PM UTC (d40fceb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/441/5841bfe...jan-ivar:d40fceb.html" title="Last updated on Dec 7, 2022, 11:05 PM UTC (d40fceb)">Diff</a>

Define default send order.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/454.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/455.html" title="Last updated on Jan 11, 2023, 10:12 PM UTC (4d7490e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/455/b93da1e...jan-ivar:4d7490e.html" title="Last updated on Jan 11, 2023, 10:12 PM UTC (4d7490e)">Diff</a>

Restore #380 after merge accident.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/425, https://github.com/w3c/webtransport/issues/458, https://github.com/w3c/webtransport/issues/459.
See https://whatpr.org/webidl/1211.html#example-domexception-derived-interface for guidance.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/460.html" title="Last updated on Jan 25, 2023, 5:52 PM UTC (213189c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/460/bb7a74b...jan-ivar:213189c.html" title="Last updated on Jan 25, 2023, 5:52 PM UTC (213189c)">Diff</a>

Align WebTransportError with guidance.

---

samples/webcodecs-echo/css/main.css
samples/webcodecs-echo/index.html
samples/webcodecs-echo/js/main.js
samples/webcodecs-echo/js/stream_worker.js

Rebase of https://github.com/w3c/webtransport/pull/415
Live demo: https://webrtc.internaut.com/wc/wtSender10/
Requires Chromium M108+ (to support BYOB reader)
Known issues: 
1. Device selection (different behavior in Chrome vs. Chrome Canary). 
2. FIXED: Non-optimal write strategy (added `await writer.ready`, removed `await` from `writer.write`, `writer.close`)
3. Server support for "cut-through" forwarding
4. Server support for `RESET_STREAM` forwarding
5. PARTIALLY FIXED: Non-optimal read strategy (removed awaits on read side, while {} loop). 
6. FIXED: Add writer.releaseLock() and reader.releaseLock()

Add WebCodecs-Echo to the samples directory

---

index.bs

Fixes #457.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/462.html" title="Last updated on Jan 25, 2023, 5:58 PM UTC (909c1c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/462/bb7a74b...jan-ivar:909c1c9.html" title="Last updated on Jan 25, 2023, 5:58 PM UTC (909c1c9)">Diff</a>

Rely on allowPooling's default value.

---

index.bs

Fixes #463 and https://github.com/w3c/webtransport/issues/450. For discussion.

Allow ∞ for incoming/outgoingHighWaterMark and incoming/outgoingMaxAge.

---

index.bs

This PR updates the protocol mapping table, so that we don't use the words `errorCode` on both sides. It also removes `STREAM_FINAL` which is not a frame specified in QUIC.
Fixes https://github.com/w3c/webtransport/issues/410.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/467.html" title="Last updated on Feb 13, 2023, 9:57 AM UTC (2a95c5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/467/d90cf90...nidhijaju:2a95c5b.html" title="Last updated on Feb 13, 2023, 9:57 AM UTC (2a95c5b)">Diff</a>

Update protocol mapping table

---

index.bs

This wraps the "Fire an event" term to its definition in the DOM spec. This is useful to clarify what this means and in particular that the event will use the `Event` interface.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/webtransport/pull/473.html" title="Last updated on Feb 16, 2023, 8:16 AM UTC (ef2efaa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/473/6e4b8b7...tidoust:ef2efaa.html" title="Last updated on Feb 16, 2023, 8:16 AM UTC (ef2efaa)">Diff</a>

Linkify "fire an event" concept to clarify steps and interface

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/472 and https://github.com/w3c/webtransport/issues/479
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/474.html" title="Last updated on Feb 24, 2023, 7:24 PM UTC (1eab7e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/474/6e4b8b7...1eab7e0.html" title="Last updated on Feb 24, 2023, 7:24 PM UTC (1eab7e0)">Diff</a>

Supporting "reliable-only"

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/466.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/468.html" title="Last updated on Mar 1, 2023, 12:56 AM UTC (fc9b0f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/468/40b002d...nidhijaju:fc9b0f1.html" title="Last updated on Mar 1, 2023, 12:56 AM UTC (fc9b0f1)">Diff</a>

Use nested steps for steps run in parallel

---

index.bs

Fixes #432 
Rebase of #437
Based on merged PR 79: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/79 which is now included in https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/482.html" title="Last updated on Mar 14, 2023, 4:17 AM UTC (8c4f7c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/482/7d621a5...8c4f7c0.html" title="Last updated on Mar 14, 2023, 4:17 AM UTC (8c4f7c0)">Diff</a>

Receiving a GOAWAY frame or DRAIN_WEBTRANSPORT_SESSION capsule

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/484.
***
<a href="https://pr-preview.s3.amazonaws.com/pthatcher/webtransport/pull/494.html" title="Last updated on Apr 11, 2023, 1:41 PM UTC (3c7ed34)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/494/5e8422f...pthatcher:3c7ed34.html" title="Last updated on Apr 11, 2023, 1:41 PM UTC (3c7ed34)">Diff</a>

Add estimatedSendRate to stats.

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/422
Rebase of https://github.com/w3c/webtransport/pull/490
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/491.html" title="Last updated on Apr 11, 2023, 2:14 PM UTC (fad80c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/491/5e8422f...fad80c6.html" title="Last updated on Apr 11, 2023, 2:14 PM UTC (fad80c6)">Diff</a>

RESET_STREAM handling

---

index.bs

The proposal for WebTransport interacting with BFCache is that we allow pages using WebTransport to enter the BFCache, but close the connection when navigating away. Then, the various promises will resolve if/when the page is navigated back to. 
The spec currently already terminates the session in the [unloading document cleanup steps](https://www.w3.org/TR/webtransport/#web-transport-context-cleanup-steps), but this PR adds a step to [queue a network task](https://www.w3.org/TR/webtransport/#webtransport-queue-a-network-task) to run [cleanup](https://www.w3.org/TR/webtransport/#webtransport-cleanup) on a WebTransport object. The network task queue will be paused when the page is navigated away from, and resumed when the page is navigated back to.
Fixes …

Specify BFCache interaction

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/332
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/501.html" title="Last updated on Apr 25, 2023, 11:22 PM UTC (92ab673)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/501/b2b4b07...92ab673.html" title="Last updated on Apr 25, 2023, 11:22 PM UTC (92ab673)">Diff</a>

State persistence

---

index.bs

This change adds support for BYOB readers for datagrams in the spec, similar to WebTransportReceiveStreams.
Fixes https://github.com/w3c/webtransport/issues/480.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/487.html" title="Last updated on Apr 24, 2023, 4:14 AM UTC (3ffe59d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/487/b2b4b07...nidhijaju:3ffe59d.html" title="Last updated on Apr 24, 2023, 4:14 AM UTC (3ffe59d)">Diff</a>

Support BYOB Readers for Datagrams

---

index.bs

As mentioned in https://github.com/w3c/webtransport/pull/500#issuecomment-1522656746, the [BFCache guidance](https://html.spec.whatwg.org/multipage/document-lifecycle.html#unloading-document-cleanup-steps) was recently updated to say we should define a stand-alone set of steps, that the HTML spec explicitly calls out to at unloading-document-cleanup time. This PR updates the spec based on this guidance, in coordination with https://github.com/whatwg/html/pull/9217.
cc @rakina
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/503.html" title="Last updated on Apr 26, 2023, 3:05 AM UTC (5bd2de8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/503/85fc448...nidhijaju:5bd2de8.html" title="Last updated on Apr 26, 2023, 3:05 AM UTC …

Update BFCache interaction

---

index.bs

See ietf-wg-webtrans/draft-ietf-webtrans-http3#115 for the corresponding protocol change.
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/509.html" title="Last updated on May 9, 2023, 5:21 AM UTC (fc0d9ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/509/7bb74aa...vasilvv:fc0d9ea.html" title="Last updated on May 9, 2023, 5:21 AM UTC (fc0d9ea)">Diff</a>

Make streamErrorCode 32-bit long

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/492.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/510.html" title="Last updated on May 9, 2023, 12:41 PM UTC (339cc0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/510/7bb74aa...jan-ivar:339cc0a.html" title="Last updated on May 9, 2023, 12:41 PM UTC (339cc0a)">Diff</a>

Add sendStream.sendOrder = n attribute.

---

index.bs

Fixes #414
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/513.html" title="Last updated on May 17, 2023, 5:27 PM UTC (c2186a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/513/cb131a6...c2186a9.html" title="Last updated on May 17, 2023, 5:27 PM UTC (c2186a9)">Diff</a>

Provide guidance on displaying a human readable error message without language info

---

index.bs

Fixes #497
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/514.html" title="Last updated on May 17, 2023, 3:49 PM UTC (982c674)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/514/cb131a6...982c674.html" title="Last updated on May 17, 2023, 3:49 PM UTC (982c674)">Diff</a>

Removing language that indicates the sendRate estimate must be absent when pooled.

---

index.bs

This change specifies _where_ the NotSupportedError and trust errors should be thrown when handling [serverCertificateHashes](https://w3c.github.io/webtransport/#dom-webtransportoptions-servercertificatehashes). It also adds explicit parameters to the certificate hash algorithms.
Fixes https://github.com/w3c/webtransport/issues/456 and fixes https://github.com/w3c/webtransport/issues/359.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/489.html" title="Last updated on Apr 27, 2023, 1:33 AM UTC (e950163)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/489/85fc448...nidhijaju:e950163.html" title="Last updated on Apr 27, 2023, 1:33 AM UTC (e950163)">Diff</a>

Throwing serverCertificateHashes related errors

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/520.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/521.html" title="Last updated on Jun 20, 2023, 11:31 PM UTC (6c00f5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/521/fefcd4d...jan-ivar:6c00f5a.html" title="Last updated on Jun 20, 2023, 11:31 PM UTC (6c00f5a)">Diff</a>

UA SHOULD divide bandwidth fairly between all streams that aren’t starved

---

samples/webcodecs-echo/index.html
samples/webcodecs-echo/js/main.js

This PR uses the RVFC API to calculate glass-glass latency as using (presentationTime - captureTime) returned from RVFC. A chart of glass-glass latency versus output frame number is displayed. 
A live demo is here:  https://webrtc.internaut.com/wc/wtSender12/

Add automated glass-glass latency calculation via RVFC

---

index.bs

The [cleanup](https://w3c.github.io/webtransport/#webtransport-cleanup) steps currently only cleans up the incoming bi- and unidirectional streams, and [[[SendStreams]] ](https://w3c.github.io/webtransport/#dom-webtransport-sendstreams-slot)and [[[ReceiveStreams]]](https://w3c.github.io/webtransport/#dom-webtransport-receivestreams-slot). This PR adds steps to cleanup the [datagrams](https://www.w3.org/TR/webtransport/#dom-webtransport-datagrams-slot) as well.
Fixes https://github.com/w3c/webtransport/issues/524.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/526.html" title="Last updated on Jul 10, 2023, 9:30 AM UTC (e935d61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/526/72763a0...nidhijaju:e935d61.html" title="Last updated …

Cleanup Datagram Streams

---

index.bs

This is a follow-up of #509. Now streamErrorCode has values in the range [0, 4294967295].
***
<a href="https://pr-preview.s3.amazonaws.com/bashi/webtransport/pull/527.html" title="Last updated on Jul 18, 2023, 5:52 AM UTC (fb01b5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/527/72763a0...bashi:fb01b5e.html" title="Last updated on Jul 18, 2023, 5:52 AM UTC (fb01b5e)">Diff</a>

Update ranges of streamErrorCode

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/533.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/535.html" title="Last updated on Aug 15, 2023, 12:03 PM UTC (947e76d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/535/b6eef8f...nidhijaju:947e76d.html" title="Last updated on Aug 15, 2023, 12:03 PM UTC (947e76d)">Diff</a>

Clarify Protocol concepts section (Section 3)

---

index.bs

Addresses https://github.com/w3c/webtransport/pull/535#discussion_r1294557018.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/538.html" title="Last updated on Aug 18, 2023, 9:12 AM UTC (9255a09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/538/0369610...nidhijaju:9255a09.html" title="Last updated on Aug 18, 2023, 9:12 AM UTC (9255a09)">Diff</a>

Add introduction to Section 3

---

samples/webcodecs-echo/index.html
samples/webcodecs-echo/js/main.js
samples/webcodecs-echo/js/stream_worker.js

Move to plotly graphing library.

Use plotly graphing library instead of Google Graphs in samples

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/446.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 19, 2023, 7:52 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fwebtransport%2Fb6eef8f292a437fcd1a878389e1fb1dd3c0de92f%2Findex.bs&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal …
```

Reject create(Uni|Bi)directionalStream() on stream ID exhaustion.

---

index.bs

As agreed in https://github.com/w3c/webtransport/issues/537.

Remove stats numOutgoingStreamsCreated & numIncomingStreamsCreated

---

index.bs

As discussed in https://github.com/w3c/webtransport/issues/537.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/546.html" title="Last updated on Sep 25, 2023, 7:09 PM UTC (8c4fdbf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/546/d0e87c9...jan-ivar:8c4fdbf.html" title="Last updated on Sep 25, 2023, 7:09 PM UTC (8c4fdbf)">Diff</a>

Add stat bytesLost

---

index.bs

Fixes #537.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/547.html" title="Last updated on Sep 26, 2023, 6:50 PM UTC (97d42f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/547/ee19ede...jan-ivar:97d42f7.html" title="Last updated on Sep 26, 2023, 6:50 PM UTC (97d42f7)">Diff</a>

Define [=underlying connection=] for connection-level stats.

---

samples/webcodecs-echo/js/stream_worker.js

When the WebCodecs encoder spits out a decoder configuration, set optimizeForLatency in the decoder configuration based on the encoder's configured latencyMode. This ensures that an encode latencyMode setting of "realtime" is paired with a decoder optimizeForLatency setting of true. This reduces decode times and glass-glass latency considerably (as much as 100 - 150ms) depending on the selected codec, resolution and number of temporal layers.   The effect is largest with the VP8 and AV1 codecs, but barely noticeable with H.264.  
When encoding AV1 at full-HD resolution and 30 fps with a target bitrate of 1 Mbps, glass-glass latency < 95 ms was observed between a client in Redmond, WA and an echo server in Santa Clara, CA.

Set optimizeForLatency in decoder configuration

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/515.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/548.html" title="Last updated on Oct 11, 2023, 2:23 PM UTC (256f792)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/548/d0e87c9...jan-ivar:256f792.html" title="Last updated on Oct 11, 2023, 2:23 PM UTC (256f792)">Diff</a>

Add SendGroup, and make sendOrder no longer nullable.

---

index.bs

Fixes #550
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/552.html" title="Last updated on Oct 17, 2023, 10:01 AM UTC (0c903a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/552/967a740...vasilvv:0c903a0.html" title="Last updated on Oct 17, 2023, 10:01 AM UTC (0c903a0)">Diff</a>

Remove timestamp from all stats objects

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/463 reopened.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/555.html" title="Last updated on Oct 18, 2023, 6:48 PM UTC (7292d72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/555/967a740...jan-ivar:7292d72.html" title="Last updated on Oct 18, 2023, 6:48 PM UTC (7292d72)">Diff</a>

Make incomingMaxAge and outgoingMaxAge nullable again.

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/556.html" title="Last updated on Oct 18, 2023, 6:56 PM UTC (b53b5d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/556/967a740...jan-ivar:b53b5d0.html" title="Last updated on Oct 18, 2023, 6:56 PM UTC (b53b5d0)">Diff</a>

Fix wrong internal slot in a note about the datagrams queue.

---

index.bs

Fixes #557
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/558.html" title="Last updated on Nov 20, 2023, 10:57 AM UTC (5dae276)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/558/967a740...vasilvv:5dae276.html" title="Last updated on Nov 20, 2023, 10:57 AM UTC (5dae276)">Diff</a>

Reject getStats() promise when the connection is closed/failed.

---

index.bs

Fixes #563.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/564.html" title="Last updated on Nov 1, 2023, 10:49 PM UTC (6519594)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/564/c177c1e...jan-ivar:6519594.html" title="Last updated on Nov 1, 2023, 10:49 PM UTC (6519594)">Diff</a>

Fix missing |promise| reference in abortSignal algorithm.

---

index.bs

Fixes #569.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/570.html" title="Last updated on Nov 21, 2023, 3:20 PM UTC (e60f0d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/570/c177c1e...jan-ivar:e60f0d1.html" title="Last updated on Nov 21, 2023, 3:20 PM UTC (e60f0d1)">Diff</a>

Move normative prose in send algortithms out of notes.

---

index.bs

Fixes #554
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/573.html" title="Last updated on Nov 21, 2023, 3:27 PM UTC (0794b98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/573/c177c1e...vasilvv:0794b98.html" title="Last updated on Nov 21, 2023, 3:27 PM UTC (0794b98)">Diff</a>

Make estimatedSendRate be `null` instead of `undefined`

---

index.bs

A first pass at updating the spec to be more independent of the underlying transport.
Fixes https://github.com/w3c/webtransport/issues/408.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/562.html" title="Last updated on Dec 5, 2023, 6:12 AM UTC (3a42e4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/562/c177c1e...nidhijaju:3a42e4c.html" title="Last updated on Dec 5, 2023, 6:12 AM UTC (3a42e4c)">Diff</a>

Update spec with transport agnostic language

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/565.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/566.html" title="Last updated on Dec 5, 2023, 10:10 PM UTC (6db61c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/566/c177c1e...jan-ivar:6db61c9.html" title="Last updated on Dec 5, 2023, 10:10 PM UTC (6db61c9)">Diff</a>

Reject in-flight write promise on network error.

---

index.bs

Fixes #518, overtaking https://github.com/w3c/webtransport/pull/568#issuecomment-1821168537.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/575.html" title="Last updated on Dec 6, 2023, 12:38 AM UTC (6fe5ddd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/575/af7ea01...jan-ivar:6fe5ddd.html" title="Last updated on Dec 6, 2023, 12:38 AM UTC (6fe5ddd)">Diff</a>

Add WebTransport.supportsReliableOnly boolean.

---

index.bs

Fix typo
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/577.html" title="Last updated on Dec 6, 2023, 2:52 PM UTC (1004496)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/577/8b74ae0...1004496.html" title="Last updated on Dec 6, 2023, 2:52 PM UTC (1004496)">Diff</a>

s/An send order/A send order/

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/426, superseding #502.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/551.html" title="Last updated on Jan 30, 2024, 11:57 PM UTC (fbc834b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/551/af7ea01...jan-ivar:fbc834b.html" title="Last updated on Jan 30, 2024, 11:57 PM UTC (fbc834b)">Diff</a>

Add writer.atomicWrite() method.

---

index.bs

This is a simplification, which will cause applications to see errors more often, but I think that it is a good one.
Closes #581.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/webtransport/pull/582.html" title="Last updated on Jan 23, 2024, 11:38 PM UTC (8be3017)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/582/607bfa8...martinthomson:8be3017.html" title="Last updated on Jan 23, 2024, 11:38 PM UTC (8be3017)">Diff</a>

Remove dependency on Data Recvd signals in cleanup

---

index.bs

This PR adds the `expiredIncoming` stat and formats the section a little bit.
Fixes https://github.com/w3c/webtransport/issues/553.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/585.html" title="Last updated on Jan 29, 2024, 3:18 AM UTC (fd3181a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/585/607bfa8...nidhijaju:fd3181a.html" title="Last updated on Jan 29, 2024, 3:18 AM UTC (fd3181a)">Diff</a>

Add expiredIncoming

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/567.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/586.html" title="Last updated on Jan 31, 2024, 12:48 AM UTC (3937549)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/586/607bfa8...nidhijaju:3937549.html" title="Last updated on Jan 31, 2024, 12:48 AM UTC (3937549)">Diff</a>

Add note about unavailability of stats

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/583.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/588.html" title="Last updated on Jan 30, 2024, 4:22 AM UTC (fcc0d0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/588/607bfa8...nidhijaju:fcc0d0d.html" title="Last updated on Jan 30, 2024, 4:22 AM UTC (fcc0d0d)">Diff</a>

Add reference for "first-strong"

---

index.bs

This PR adds an example for reading datagrams and one for receive streams with a BYOB reader.
Fixes https://github.com/w3c/webtransport/issues/131.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/584.html" title="Last updated on Jan 31, 2024, 1:09 AM UTC (69988a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/584/3d22dbb...nidhijaju:69988a2.html" title="Last updated on Jan 31, 2024, 1:09 AM UTC (69988a2)">Diff</a>

Add examples for reading with BYOB readers

---

index.bs

This PR allows more aggressive garbage collection, by not allowing it only if there is a lock on readable streams or if there is a relevant promise that is still being awaited.
Fixes https://github.com/w3c/webtransport/issues/560.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/587.html" title="Last updated on Feb 14, 2024, 1:54 AM UTC (25b7202)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/587/363c152...nidhijaju:25b7202.html" title="Last updated on Feb 14, 2024, 1:54 AM UTC (25b7202)">Diff</a>

Add more conditions for garbage collection

---

index.bs

This PR links to the IETF webtransport overview doc's definition of datagrams for added clarification.
Fixes https://github.com/w3c/webtransport/issues/542.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/591.html" title="Last updated on Feb 24, 2024, 8:29 AM UTC (0e482d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/591/bef2379...nidhijaju:0e482d3.html" title="Last updated on Feb 24, 2024, 8:29 AM UTC (0e482d3)">Diff</a>

Add spec reference for datagrams definition

---

index.bs

Fixes #544 (for discussion).
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/574.html" title="Last updated on Feb 27, 2024, 10:50 PM UTC (701e688)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/574/607bfa8...jan-ivar:701e688.html" title="Last updated on Feb 27, 2024, 10:50 PM UTC (701e688)">Diff</a>

Add anticipatedConcurrentIncoming[Bi/Uni]directionalStreams attributes & constructor arg

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/508.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/592.html" title="Last updated on Feb 27, 2024, 8:33 AM UTC (d502680)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/592/09dc62d...nidhijaju:d502680.html" title="Last updated on Feb 27, 2024, 8:33 AM UTC (d502680)">Diff</a>

Add example for server certificate hashes

---

index.bs

Fixes #541.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/593.html" title="Last updated on Feb 28, 2024, 12:41 AM UTC (6133b23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/593/8db4c49...jan-ivar:6133b23.html" title="Last updated on Feb 28, 2024, 12:41 AM UTC (6133b23)">Diff</a>

Default to allow the server to create >= 100 uni and >=100 bidi streams.

---

index.bs

Update normative RFC references to replace "Internet Draft" status with "Proposed Standard"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/594.html" title="Last updated on Feb 28, 2024, 3:36 PM UTC (1e3cb0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/594/2272f05...1e3cb0a.html" title="Last updated on Feb 28, 2024, 3:36 PM UTC (1e3cb0a)">Diff</a>

Update normative RFC references

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/523.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/595.html" title="Last updated on Mar 26, 2024, 11:27 PM UTC (a71f242)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/595/9dd3692...nidhijaju:a71f242.html" title="Last updated on Mar 26, 2024, 11:27 PM UTC (a71f242)">Diff</a>

Add note about retransmissions and send order

---

index.bs

Fixes #607 (modulo https://github.com/w3c/webtransport/issues/608).
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/609.html" title="Last updated on Jul 16, 2024, 10:46 PM UTC (419ab3f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/609/55eb163...jan-ivar:419ab3f.html" title="Last updated on Jul 16, 2024, 10:46 PM UTC (419ab3f)">Diff</a>

Add required or =0 in WebIDL to document stats SHALL be present (except RTT ones)

---

samples/webcodecs-echo/index.html
samples/webcodecs-echo/js/main.js
samples/webcodecs-echo/js/stream_worker.js

The WebTransport Echo sample has been updated to support the following: 
- HEVC encode and decode. Works only on Chrome Canary with flags set: 
--enable-features=PlatformHEVCEncoderSupport,WebRtcAllowH265Send,WebRtcAllowH265Receive --force-fieldtrials="WebRTC-Video-H26xPacketBuffer/Enabled/"
- Glass-to-glass latency and encode time charts. This had been broken by changes to the WebCodecs and RVFC implementations on Chrome, but is now fixed. 
Revised sample live site: 
https://webrtc.internaut.com/wc/wtSender13/

Update WebTransport Echo in samples directory with HEVC, display glass to glass delay

---

index.bs

Updates connection algorithm so that any HTTP redirection response is treated as a network error and is indistinguishable from any 3XX,5XX error. Adds note with motivation for why this being done. 
Fixes: #499
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/612.html" title="Last updated on Aug 27, 2024, 2:13 PM UTC (97ddea4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/612/d5781c2...97ddea4.html" title="Last updated on Aug 27, 2024, 2:13 PM UTC (97ddea4)">Diff</a>

Redirection treated as a network error

---

index.bs

Fixes #536. Right now this seems only defined for HTTP/3, so that's what I went with. Is this what we want?
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/598.html" title="Last updated on Sep 17, 2024, 3:13 AM UTC (6b82382)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/598/55eb163...jan-ivar:6b82382.html" title="Last updated on Sep 17, 2024, 3:13 AM UTC (6b82382)">Diff</a>

Add protocols constructor argument to WebTransport + protocol read arg

---

index.bs

Fixes #559. For discussion.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/603.html" title="Last updated on Oct 8, 2024, 11:22 PM UTC (44a80cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/603/3363834...jan-ivar:44a80cb.html" title="Last updated on Oct 8, 2024, 11:22 PM UTC (44a80cb)">Diff</a>

Add stats.atSendCapacity

---

index.bs

Fixes #618
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/619.html" title="Last updated on Oct 21, 2024, 2:00 PM UTC (898287e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/619/3a324bf...898287e.html" title="Last updated on Oct 21, 2024, 2:00 PM UTC (898287e)">Diff</a>

Add notes on receiver-side stream availability

---

index.bs

As discussed in https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/103
This is NOT the only place where this state is used.  That one needs a few more grey matter cycles before I have a resolution.  I'll open an issue instead.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/webtransport/pull/580.html" title="Last updated on Jan 14, 2025, 3:38 PM UTC (ba41dea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/580/607bfa8...martinthomson:ba41dea.html" title="Last updated on Jan 14, 2025, 3:38 PM UTC (ba41dea)">Diff</a>

Rename "Data Recvd" to "all data committed"

---

index.bs

Fixes #615
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/632.html" title="Last updated on Feb 22, 2025, 8:18 PM UTC (40449bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/632/a806432...40449bb.html" title="Last updated on Feb 22, 2025, 8:18 PM UTC (40449bb)">Diff</a>

Adjust estimatedSendRate definition to exclude framing overhead

---

index.bs

Fixes https://github.com/w3c/webtransport/issues/610 (builds on https://github.com/w3c/webtransport/pull/620)
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/629.html" title="Last updated on Feb 21, 2025, 3:10 PM UTC (9cf8d2c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/629/f2bfc64...jan-ivar:9cf8d2c.html" title="Last updated on Feb 21, 2025, 3:10 PM UTC (9cf8d2c)">Diff</a>

Add datagrams.createWritable({sendGroup, sendOrder})

---

index.bs

Partial fix for #616.
Do we likewise need on overview doc for draining?
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/640.html" title="Last updated on Mar 26, 2025, 3:13 PM UTC (5bab511)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/640/e5abd59...jan-ivar:5bab511.html" title="Last updated on Mar 26, 2025, 3:13 PM UTC (5bab511)">Diff</a>

Reference overview doc for protocol negotiation

---

index.bs

Fixes #616.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/645.html" title="Last updated on Apr 22, 2025, 11:13 PM UTC (7fe12e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/645/6db6cae...nidhijaju:7fe12e8.html" title="Last updated on Apr 22, 2025, 11:13 PM UTC (7fe12e8)">Diff</a>

Replaces references of HTTP/3 spec with Overview

---

index.bs

This reverts commit 34ef7b2c2e91b1d337015d3b71028ea0e144d54d now that #623 is closed.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/657.html" title="Last updated on May 21, 2025, 3:05 PM UTC (d472a61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/657/399f6c2...jan-ivar:d472a61.html" title="Last updated on May 21, 2025, 3:05 PM UTC (d472a61)">Diff</a>

Revert "Mark serverCertificateHashes as at risk"

---

index.bs

Turns out, this is not quite that easy, so it was worth chasing this down.
Waiting on a resolution to https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/issues/124 before I can resolve the TODO.
Closes #642.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/webtransport/pull/648.html" title="Last updated on Apr 23, 2025, 12:26 AM UTC (b60765e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/648/d5a6eec...martinthomson:b60765e.html" title="Last updated on Apr 23, 2025, 12:26 AM UTC (b60765e)">Diff</a>

Add some guidance on how to pick maxDatagramSize

---

index.bs

This fixes https://github.com/w3c/webtransport/issues/664, but there's still some work to be done for https://github.com/w3c/webtransport/issues/647.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/666.html" title="Last updated on Jun 17, 2025, 11:08 PM UTC (c6ac55a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/666/2c7fa24...nidhijaju:c6ac55a.html" title="Last updated on Jun 17, 2025, 11:08 PM UTC (c6ac55a)">Diff</a>

Remove GOAWAY and update drain

---

index.bs

This also goes through and cleans up all the mess around RESET_STREAM. It's not perfect: we are now using that term (RESET_STREAM) to refer to a RESET_STREAM_AT frame (h3) or a WT_RESET_STREAM capsule (h2).
Closes #654.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/webtransport/pull/667.html" title="Last updated on Jul 1, 2025, 12:20 AM UTC (b32af85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/667/2c7fa24...martinthomson:b32af85.html" title="Last updated on Jul 1, 2025, 12:20 AM UTC (b32af85)">Diff</a>

API for Reliable Resets

---

index.bs

Fixes #236. I recommend [whitespace diff](https://github.com/w3c/webtransport/pull/670/files?diff=unified&w=1) for review.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/670.html" title="Last updated on Jul 1, 2025, 2:48 PM UTC (42ceacd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/670/8aa5013...jan-ivar:42ceacd.html" title="Last updated on Jul 1, 2025, 2:48 PM UTC (42ceacd)">Diff</a>

Fix threading model of send datagrams algorithm
