w3c/webtransport

include/respec-config.js, index.html
Reference IETF docs for ALPN, transport parameters, etc
=> Reference IETF docs

include/respec-config.js
Fix issues in references that are causing a respec break.
May address Issue https://npm.pkg.github.com/pthatcherg/web-transport/issues/9
=> Fix bad reference entries

index.html
Fix for Issue https://npm.pkg.github.com/pthatcherg/web-transport/issues/9
Applying this fix should allow the spec to render without errors.
=> Remove bad links

include/respec-config.js
Update links now that the draft is in WICG.
=> Fix editor's draft and Issues links

include/respec-config.js, index.html
Add more text inspired by questions in TAG Security and Privacy Questionnaire.
=> Expand Security Considerations section

explainer.md, include/respec-config.js, index.html
First attempt at this.  It can probably use a lot of eyeballs.
=> Switch to using WHATWG streams

explainer.md
- Use for await on readable streams
- Fix small typos
- Assume WebTransport streams implement a Body mixin so .arrayBuffer()
can read the entire stream.
=> Modernize the explainer examples

explainer.md
The recency should be obvious based on the commit log.
=> Remove last updated from the explainer

index.bs, index.html
Also fix Bikeshed compile errors
=> Consistently reference the same version of WebIDL spec

index.bs, index.html
The "new" state is unused. Remove it.
=> Remove the "new" state

index.bs, index.html
Fix https://github.com/WICG/web-transport/issues/81
=> Change .onerror to .closed

index.bs, index.html
=> Remove stream ID per discussion in #74

index.bs, index.html
=> Fix one link to QuicTransportBase

index.bs, index.html
=> Remove disableRetransmissions

index.bs, index.html
"resolved" => "fulfilled" promises
=> Use proper terminology for promises

index.bs
Fixes https://github.com/WICG/web-transport/issues/28
=> Dont transition from failed to closed.

index.bs
Fixes https://github.com/WICG/web-transport/issues/63
=> Fix description of bidirectional streams.

index.bs
Fix https://github.com/WICG/web-transport/issues/69
=> Fix createSendStream text.

index.bs, index.html
Fixes https://github.com/WICG/web-transport/issues/73 with option B.
=> Remove readonly attribute WebTransport transport

index.bs
=> Simplify examples

explainer.md
Reflect the interface changes #134 and #135.
Also delete trailing whitespaces.
=> Update explainer.md 

index.bs
=> Introduce WebTransport.ready

index.bs
Fix for Issue https://github.com/w3c/webtransport/issues/154
=> Fix out of date references

index.bs
Fix for Issue https://github.com/w3c/webtransport/issues/156
=> Add reference to QUIC datagram draft

index.bs
This PR adds a complete example.
=> Add a complete example

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/171.html" title="Last updated on Nov 25, 2020, 8:47 PM UTC (966b65b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/171/ddbf3ce...966b65b.html" title="Last updated on Nov 25, 2020, 8:47 PM UTC (966b65b)">Diff</a>
=> duplicate # in fragment definition

index.bs
Fixes #70.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/202.html" title="Last updated on Feb 27, 2021, 5:28 PM UTC (e3c5627)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/202/a813b4c...jan-ivar:e3c5627.html" title="Last updated on Feb 27, 2021, 5:28 PM UTC (e3c5627)">Diff</a>
=> Fix races and respect max stream limit when creating streams.

index.bs
Addresses #235.
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/238.html" title="Last updated on Mar 31, 2021, 5:01 PM UTC (b94fd68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/238/dc59f89...vasilvv:b94fd68.html" title="Last updated on Mar 31, 2021, 5:01 PM UTC (b94fd68)">Diff</a>
=> Change stream reset code to 8 bits.

index.bs
Fixes #239.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/241.html" title="Last updated on Mar 31, 2021, 9:25 PM UTC (6dc7337)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/241/dc59f89...jan-ivar:6dc7337.html" title="Last updated on Mar 31, 2021, 9:25 PM UTC (6dc7337)">Diff</a>
=> Inline mixins IncomingStream and OutgoingStream.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/hst-m/webtransport/pull/262.html" title="Last updated on May 17, 2021, 11:31 AM UTC (4930bfd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/262/76d2423...hst-m:4930bfd.html" title="Last updated on May 17, 2021, 11:31 AM UTC (4930bfd)">Diff</a>
=> Fix Example

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/275.html" title="Last updated on Jun 14, 2021, 6:10 AM UTC (d4f7cb7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/275/2a0ca65...d4f7cb7.html" title="Last updated on Jun 14, 2021, 6:10 AM UTC (d4f7cb7)">Diff</a>
=> [Editorial] Merge UnidirectionalStreamsTransport into WebTransport

index.bs
The error object hasn't been decided yet, so it's TBD (#252).
Fixes #268.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/281.html" title="Last updated on Jun 23, 2021, 5:03 AM UTC (11e1784)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/281/dec79ad...11e1784.html" title="Last updated on Jun 23, 2021, 5:03 AM UTC (11e1784)">Diff</a>
=> Describe session termination not initiated by the client

index.bs
=> [Editorial] Remove WebTransport.[[OutgoingStreams]]

index.bs
Fixes: #292
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/300.html" title="Last updated on Jul 1, 2021, 11:09 AM UTC (ec183f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/300/3e770d9...ec183f1.html" title="Last updated on Jul 1, 2021, 11:09 AM UTC (ec183f1)">Diff</a>
=> Remove .state and .onstatechange attributes

index.bs
Fixes #93.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/299.html" title="Last updated on Jun 30, 2021, 10:07 AM UTC (288d494)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/299/049ba58...288d494.html" title="Last updated on Jun 30, 2021, 10:07 AM UTC (288d494)">Diff</a>
=> Allow storing/discarding datagrams while connecting

index.bs
Fixes #277.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/303.html" title="Last updated on Jul 2, 2021, 3:04 AM UTC (ef3004c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/303/da0b77e...ef3004c.html" title="Last updated on Jul 2, 2021, 3:04 AM UTC (ef3004c)">Diff</a>
=> Remove SendStreamParameters

index.bs
Fixes #117.
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/313.html" title="Last updated on Jul 19, 2021, 10:54 PM UTC (8f0962b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/313/789727d...vasilvv:8f0962b.html" title="Last updated on Jul 19, 2021, 10:54 PM UTC (8f0962b)">Diff</a>
=> Make fingerprint matching case-insensitive.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/315.html" title="Last updated on Jul 21, 2021, 8:34 PM UTC (406a9b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/315/789727d...vasilvv:406a9b5.html" title="Last updated on Jul 21, 2021, 8:34 PM UTC (406a9b5)">Diff</a>
=> Update Security Considerations to reflect WebTransport over HTTP better

security-questionnaire.md
=> Answer the security questionnaire

index.bs
Fixes #350.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/357.html" title="Last updated on Sep 16, 2021, 10:18 AM UTC (d2ab1a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/357/9ff7a84...d2ab1a3.html" title="Last updated on Sep 16, 2021, 10:18 AM UTC (d2ab1a3)">Diff</a>
=> Replace "fingerprint" with "hash" in various names

index.bs
Fixes #188.
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/312.html" title="Last updated on Nov 10, 2021, 6:56 PM UTC (0f08c4a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/312/94d996e...vasilvv:0f08c4a.html" title="Last updated on Nov 10, 2021, 6:56 PM UTC (0f08c4a)">Diff</a>
=> Must not provide any credentials via HTTP headers

index.bs
While reviewing, I found the cleanup steps a bit hard to follow. Hopefully this helps. @yutakahirano WDYT?
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/380.html" title="Last updated on Dec 7, 2021, 7:03 PM UTC (4c980a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/380/3ddc1a8...jan-ivar:4c980a3.html" title="Last updated on Dec 7, 2021, 7:03 PM UTC (4c980a3)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/380.html" title="Last updated on Mar 15, 2022, 11:57 AM UTC (87252ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/380/e3c2cfc...jan-ivar:87252ab.html" title="Last updated on Mar 15, 2022, 11:57 AM UTC (87252ab)">Diff</a>
=> Simplify cleanup steps by avoiding type variance.

explainer.md
@vasilvv noted some problems with the text that was tweaked in #399, so here's a new version.
=> Reword HTTP/2 and HTTP/3 pieces of explainer

samples/echo/client.css, samples/echo/client.js, samples/echo/index.html, samples/echo/py-server/ipv4_echo_server.py, samples/echo/py-server/ipv6_echo_server.py, samples/echo/py-server/runecho, samples/echo/py-server/webrtc.internaut.com/cert.pem, samples/echo/py-server/webrtc.internaut.com/chain.pem, samples/echo/py-server/webrtc.internaut.com/fullchain.pem, samples/echo/py-server/webrtc.internaut.com/privkey.pem
Creates the sampnles directory, then adds the simple echo demo (both client and server).
=> Add simple echo sample

index.bs
Fixes #442.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/443.html" title="Last updated on Dec 8, 2022, 1:06 AM UTC (97dc5c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/443/5841bfe...jan-ivar:97dc5c9.html" title="Last updated on Dec 8, 2022, 1:06 AM UTC (97dc5c9)">Diff</a>
=> Use USVString for closeInfo.reason

explainer.md, use-cases.md
Remove reference to out-of-scope p2p communications. Fixes #447.
=> Update explainer.md and use-cases.md

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/webtransport/pull/465.html" title="Last updated on Feb 8, 2023, 2:10 AM UTC (ca0a23d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/465/d90cf90...nidhijaju:ca0a23d.html" title="Last updated on Feb 8, 2023, 2:10 AM UTC (ca0a23d)">Diff</a>
=> Add name to Editors list

index.bs
Fixes #483.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/488.html" title="Last updated on Mar 3, 2023, 3:53 PM UTC (bd094b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/488/04d7e34...jan-ivar:bd094b0.html" title="Last updated on Mar 3, 2023, 3:53 PM UTC (bd094b0)">Diff</a>
=> Revert #421.

index.bs, index.html
A rough attempt at putting some words down.
You will note that the privacy mitigations here are pretty unsatisfactory.  In short, we don't have any.  That's just how the web rolls right now and I don't think that we need to spend a lot of time on trying to invent a solution.  The only solution I'm aware of involves serious degradations in performance, either by disabling concurrency across sites or by artificially limiting network performance.  Even then, it's not clear that these tricks will do that much to help.
But at least we're not really making things worse.
In writing this, I also realized that much of the text in this section on pooled sessions was out of date.  Using the network partition key means that we don't need to worry about pooling happening in cases where it should not. …
=> Networking privacy considerations

index.bs
Fixes #505
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/512.html" title="Last updated on May 17, 2023, 3:22 PM UTC (0d06896)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/512/cb131a6...0d06896.html" title="Last updated on May 17, 2023, 3:22 PM UTC (0d06896)">Diff</a>
=> Update normative key words

index.bs
Fixes #446.
***
<a href="https://pr-preview.s3.amazonaws.com/vasilvv/web-transport/pull/572.html" title="Last updated on Nov 21, 2023, 2:58 PM UTC (1022963)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/572/c177c1e...vasilvv:1022963.html" title="Last updated on Nov 21, 2023, 2:58 PM UTC (1022963)">Diff</a>
=> Add a `waitUntilAvailable` option to stream creation

index.bs
Fixes #596 (for discussion).
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/599.html" title="Last updated on Apr 15, 2024, 5:01 PM UTC (294ba11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/599/4208ac5...jan-ivar:294ba11.html" title="Last updated on Apr 15, 2024, 5:01 PM UTC (294ba11)">Diff</a>
=> Support relative URLs.

index.bs
Fixes #601.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/602.html" title="Last updated on May 21, 2024, 8:45 PM UTC (87f1cac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/602/f82f665...jan-ivar:87f1cac.html" title="Last updated on May 21, 2024, 8:45 PM UTC (87f1cac)">Diff</a>
=> Set [[PromiseIsHandled]] on wt.ready and wt.closed.

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/webtransport/pull/617.html" title="Last updated on Sep 10, 2024, 11:16 PM UTC (4a886d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/617/3363834...martinthomson:4a886d7.html" title="Last updated on Sep 10, 2024, 11:16 PM UTC (4a886d7)">Diff</a>
=> Remove some junk from a heading

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/630.html" title="Last updated on Feb 11, 2025, 3:29 PM UTC (b3332b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/630/f2bfc64...b3332b6.html" title="Last updated on Feb 11, 2025, 3:29 PM UTC (b3332b6)">Diff</a>
=> Updating editors

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/pull/631.html" title="Last updated on Feb 12, 2025, 9:32 PM UTC (c6fc636)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/631/a806432...c6fc636.html" title="Last updated on Feb 12, 2025, 9:32 PM UTC (c6fc636)">Diff</a>
=> Update editors to include JIB

index.bs
Fixes #626.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/634.html" title="Last updated on Feb 25, 2025, 11:48 PM UTC (3b9f8b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/634/a806432...jan-ivar:3b9f8b2.html" title="Last updated on Feb 25, 2025, 11:48 PM UTC (3b9f8b2)">Diff</a>
=> Add missing tasks in parallel steps

index.bs
Fixes #624.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/webtransport/pull/638.html" title="Last updated on Mar 24, 2025, 11:48 PM UTC (3e37d39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webtransport/638/e5abd59...jan-ivar:3e37d39.html" title="Last updated on Mar 24, 2025, 11:48 PM UTC (3e37d39)">Diff</a>
=> Remove wt.datagrams.writable and fix cleanup.

index.bs
=> Fix link to [=cross-site recognition=]

index.bs
=> Explain that chunk boundaries are not preserved on reception

README.md
=> Updating hosted samples in readme

samples/webcodecs-echo/js/main.js, samples/webcodecs-echo/js/stream_worker.js
I got it working to a point. The wheels are spinning, however the VideoDecoder is producing 0x0 video frames in Safari still. More to investigate, but suggest we iterate and merge this to make progress.
=> Clean up webcodecs-echo sample to work in Safari using spec MSTP/VTG
